# _config.yml

# Site settings
title: "Your Research Group Name"
email: "your.email@example.com"
description: >-
  Welcome to the official website of [Your Research Group Name]. We conduct cutting-edge research in [your field].
baseurl: "" # Change if using a subpath
url: "http://yourwebsite.com" # Change to your website URL
github_username: "yourgithub"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  people:
    output: true
  research:
    output: true
  publications:
    output: true

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: People
    url: /people
  - title: Publications
    url: /publications
  - title: News
    url: /news
  - title: Contact
    url: /contact

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_people"
      type: "people"
    values:
      layout: "person"
  - scope:
      path: "_research"
      type: "research"
    values:
      layout: "research"
  - scope:
      path: "_publications"
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "news"
