# _config.yml

# Site settings
title: "Klem Research Group"
email: "HeidiKlem@lsu.edu"
description: >-
  Welcome to the official website of the Klem Research Group.
baseurl: "" # Change if using a subpath
url: "" # Change to your website URL
github_username: "klem-research-group"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  people:
    output: true
  research:
    output: true
  publications:
    output: true
  news:
    output: true

# Navigation (Ensure Proper List Formatting)
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "People"
    url: "/people"
  - title: "Publications"
    url: "/publications"
  - title: "News"
    url: "/news"
  - title: "Contact"
    url: "/contact"

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_people"
      type: "people"
    values:
      layout: "person"
  - scope:
      path: "_research"
      type: "research"
    values:
      layout: "research"
  - scope:
      path: "_publications"
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "news"


