# _config.yml

# Site settings
title: "Your Research Group Name"
email: "your.email@example.com"
description: >-
  Welcome to the official website of [Your Research Group Name]. We conduct cutting-edge research in [your field].
baseurl: "" # Change if using a subpath
url: "http://yourwebsite.com" # Change to your website URL
github_username: "yourgithub"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  people:
    output: true
  research:
    output: true
  publications:
    output: true

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: People
    url: /people
  - title: Publications
    url: /publications
  - title: News
    url: /news
  - title: Contact
    url: /contact

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_people"
      type: "people"
    values:
      layout: "person"
  - scope:
      path: "_research"
      type: "research"
    values:
      layout: "research"
  - scope:
      path: "_publications"
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "news"

# Layouts Directory
layouts:
  default: "_layouts/default.html"
  person: "_layouts/person.html"
  research: "_layouts/research.html"
  publication: "_layouts/publication.html"
  news: "_layouts/news.html"

# Pages
pages:
  - title: Home
    path: "index.md"
  - title: Research
    path: "research.md"
  - title: People
    path: "people.md"
  - title: Publications
    path: "publications.md"
  - title: News
    path: "news.md"
  - title: Contact
    path: "contact.md"

# Sample Data Files
_data:
  people: "_data/people.yml"
  research: "_data/research.yml"
  publications: "_data/publications.yml"
  news: "_data/news.yml"

# Layout Files
_layouts:
  default: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ page.title }}</title>
      <link rel="stylesheet" href="/assets/css/style.css">
    </head>
    <body>
      <header>
        <nav>
          <ul>
            {% for item in site.navigation %}
              <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endfor %}
          </ul>
        </nav>
      </header>
      <main>
        {{ content }}
      </main>
      <footer>
        <p>&copy; {{ site.time | date: '%Y' }} Your Research Group</p>
      </footer>
    </body>
    </html>

  person: |
    ---
    layout: default
    ---
    <h1>{{ page.name }}</h1>
    <p><strong>Role:</strong> {{ page.role }}</p>
    <p>{{ content }}</p>

  research: |
    ---
    layout: default
    ---
    <h1>{{ page.title }}</h1>
    <p>{{ content }}</p>

  publication: |
    ---
    layout: default
    ---
    <h1>{{ page.title }}</h1>
    <p><strong>Authors:</strong> {{ page.authors }}</p>
    <p><strong>Journal:</strong> {{ page.journal }}</p>
    <p>{{ content }}</p>

  news: |
    ---
    layout: default
    ---
    <h1>{{ page.title }}</h1>
    <p><strong>Date:</strong> {{ page.date }}</p>
    <p>{{ content }}</p>

# Example Data
_data:
  people.yml: |
    - name: "Dr. Jane Doe"
      role: "Principal Investigator"
      bio: "Expert in chemical biology and nanomaterials."

  research.yml: |
    - title: "Nanomaterials for Drug Delivery"
      description: "Developing innovative nanocarriers for targeted therapy."

  publications.yml: |
    - title: "Advances in Biochemistry"
      authors: "Doe, J.; Smith, A."
      journal: "Journal of Chemistry, 2023."

  news.yml: |
    - title: "New Research Grant Awarded!"
      date: "2024-03-01"
      content: "Our lab has received funding for new nanomedicine research."

